### ISSUE TITLE
添加将右半部分更换为白色字体的选项

### ISSUE THREAD

**Issue by ghost** [nulla2011/bluearchive-logo#16]

**Comment by huankong233** [comment]
> _No description provided._

可以尝试本 [项目](https://github.com/huankong233/balogo-ts) [demo](https://balogo.huankong.top/?textRColor=rgb(255,255,255)&bgColor=gray)

![demo](https://balogo.huankong.top/?textRColor=rgb(255,255,255)&bgColor=gray)
