### ISSUE TITLE
实现uri api生成？

### ISSUE THREAD

**Issue by swift-lee** [nulla2011/bluearchive-logo#5]
例如 /ba-logo?bg=tp%26text1=Blue%26text2=Archive ，返回一张背景透明的图

**Comment by bywhite0** [comment]
纯前端项目没法实现 API 吧

**Comment by huankong233** [comment]
> 例如 /ba-logo?bg=tp%26text1=Blue%26text2=Archive ，返回一张背景透明的图

已实现 https://github.com/huankong233/balogo-ts
